# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb55b7cdbaee198c46ffafb8a5a4c7006cd940094dd2b02ff6bd364975ec2ae36bb83894f90f3ca61ed65f02bb329e86997536d373ccfaaba3695c632ddb755a

test:
  secret_key_base: 10a0473f168a1cdeed559d1a80803b1bc8693190dae21d74e0a3a60985fac4483140953851f4cb8febe154e8ae76d5b394c7b8c866d5e2804e8d28cf23d5651f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
